id: P4A2DE330
initial_creation_type: input
source_metadata:
  title: Dilgo Khyentse Rinpoche Series
  language: pt
  description: 'Texts by and about Kyabje Dilgo Khyentse Rinpoche, Tashi Paljor (dil
    mgo mkhyen brtse bkra shis dpal ''byor, 1910-1991):'
  volume:
    426ac632ff934413acfafb864218b836:
      title: Advice to Three-Year Retreatants
      parent: Advice
    ffc222ae044a46a8b3e079153d4ec46b:
      title: Heart Advice in Four Lines
      parent: Advice
    8237ea4358b64243adbfee86b65e8009:
      title: Letter of Advice to Jamyang Gyaltsen
      parent: Advice
    d4d96dd72ead426a988637d738807b96:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Aspiration Prayers
    86505302c10f4045b19767a7437e4b86:
      title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
        for Mind Training'
      parent: Aspiration Prayers
    1860bb5fbbfe41f0a9a67a73bc3c3c4b:
      title: 'The Vidyādharas'' Words of Truth: An Aspiration Connected with the Stages
        of the Path of the Three Roots, from the Heart Essence of the Vast Expanse'
      parent: Aspiration Prayers
    a209d6a9b3dc454694c878bc8ebab345:
      title: 'Wisdom''s Melody: An Aspiration to Realize Madhyamaka, Mahāmudrā, and
        Mahā Ati'
      parent: Aspiration Prayers
    3506a1ae481548e38a714b487a1325bc:
      title: 'Wondrous Light of Lunar Nectar: The Biography of Chatral Kunga Palden,
        a Yogin of the Supreme Vehicle'
      parent: Biographies
    3e17796b58624ca99938d76667715b6b:
      title: Calling the Guru From Afar
      parent: Calling the Guru from Afar
    fd7410355ddd462d99ec56727edd9fe8:
      title: Calling the Guru from Afar
      parent: Calling the Guru from Afar
    e36690ed733e4adc866f323357fe7ac1:
      title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the
        Everpresent Gurus'
      parent: Calling the Guru from Afar
    8bb13254907c4281ab0e1ef7ab31413e:
      title: 'Repository of Every Form of Dharma That Might Be Wished For: A Catalogue
        to the Published Miscellaneous Writings of the Venerable Guru Jamyang Chökyi
        Lodrö'
      parent: Catalogues
    e58bc381b3d049a49291dc6e8a313967:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    566c2c7648a04fa98bfbf4d1c2e791d9:
      title: 'The Sage who Dispels Mind’s Anguish: Advice from the Guru, the Gentle
        Protector Mañjuśrī on the Means of Accomplishing the Yogas of Śamatha and
        Vipaśyanā'
      parent: Commentaries
    e673b31358cc48e2917cd4ba99eb1e6c:
      title: 'Shower of Indestructible Splendour: A Self-Initiation for the Guru Practice
        of the Vidyādhara Assembly, from the Heart-Essence of the Vast Expanse'
      parent: Empowerment Rites
    c34f233fd4214de593ab588b19f390e7:
      title: 'A Garland of Vajra Words: A Prayer to the Guru'
      parent: Guru Rinpoche Prayers
    606ea944d8c7494288969580cf6181a1:
      title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in
        Eight Chapters'
      parent: Guru Rinpoche Prayers
    c22e5d1b9d2c46019a7b09b5f8db2473:
      title: Guru Yoga – A Rang Rig Ma Chö
      parent: Guru Yoga
    09c29d74a64c42388a18d9060b73fcdf:
      title: 'Guru Yoga: The Complete Path of Sūtra And Tantra'
      parent: Guru Yoga
    d7b58a26d76e49a2bbbd8abdcda1267a:
      title: 'The Quintessence of the Profound Path: A Concise Guide to the Stages
        of Visualization for the Guru Yoga of the Seven-Line Supplication, A Shower
        of Blessings'
      parent: Guru Yoga
    0e5f19406d19484683967242f511f4d1:
      title: 'The Sun of Ambrosial Wisdom: A Guru Yoga of Dharmarāja Sakya Paṇḍita'
      parent: Guru Yoga
    e4593e93dc4942fa8f3f97a3b8ecc01b:
      title: A History of Dzongsar Monastery
      parent: History
    29641a02de5b4d95a01ea46d6b5052ac:
      title: 'Beautiful Clouds of Blessings: A Prayer to the Lineage Masters of the
        Heart Essence of the Vast Expanse from the Great Perfection'
      parent: Lineage Prayers
    604c9fcebb624272bae68fa0f789c55f:
      title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
      parent: Lineage Prayers
    1a6bc4fc6a2c41849af06bc5c1282a21:
      title: Supplication to the Lineage of the Heart Essence of the Vast Expanse
      parent: Lineage Prayers
    e92fa494ec504617940922c3b2b6df84:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Lineage Prayers
    d1e3c5a3294b4449ab9c236aa390767c:
      title: Ambrosia for the Mind
      parent: Lojong
    55bac0a0803c4c80814d1234be6bdd4b:
      title: Prayer for the Long Life of Dzongsar Jamyang Khyentse Rinpoche
      parent: Long Life Prayers
    59454bf14714401797ccadefb4aabec3:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    bf3a5a18abd44f0590f37740c38d1df8:
      title: 'The Vajra Sitar of Immortality: A Prayer for the Long Life of the Fourth
        Incarnation of Terchen Chokgyur Lingpa'
      parent: Long Life Prayers
    d05fc374c4874ac1965a326fa1f0ffaa:
      title: 'True Words to Accomplish Immortality: A Longevity Prayer to the Tulku
        of Jamyang Khyentse, Thupten Chökyi Gyatso'
      parent: Long Life Prayers
    df428891aa344d85a9bba7244de7c556:
      title: A Prayer to Dilgo Khyentse Rinpoche
      parent: Prayers
    d36a4ef59f8445f78dd450eb9ebde2d6:
      title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
      parent: Prayers
    6499b4b1e32f4a1787b5553ce9f39768:
      title: Invocation of the Vidyādhara Gurus
      parent: Prayers
    523c9b980b3540efac8733ebf1337a02:
      title: 'Light of Compassion: A Prayer to the Wisdom Ḍākinīs'
      parent: Prayers
    efc808f4227640d989dd06dfdfe46118:
      title: Prayer for the Fulfilment of Aspirations
      parent: Prayers
    a11abd492d88400faa41206460a9e207:
      title: Prayer to Khandro Tsering Chödrön
      parent: Prayers
    3f502d581f524f9e83bb5f24c0c88e80:
      title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen
        Rabjam'
      parent: Prayers
    08f6d8f2ef8d4ffdb147348a25b9a45b:
      title: 'The Potent Nectar of Accomplishment: A Prayer and Supplication to the
        Vidyādhara Gurus of the Three Lineages'
      parent: Prayers
    89d0822addc046b6a5b90255ec66db2a:
      title: The Prayer to Swiftly Fulfil All Wishes
      parent: Prayers
    3c9c8353da2f42f1935ca6c5c9d9ce2c:
      title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
      parent: Prayers
    fb709853cd2343b88a2e17b37dd4685a:
      title: 'The Quintessence of Marvellous Nectar: A Prayer Based on the Liberational
        Life of the Gentle Protector Guru'
      parent: Prayers
    2b5de422799d42118af4ac90f0b41290:
      title: 'The Swift Bestowal of Blessings: A Prayer to the Glorious Protector
        Guru'
      parent: Prayers
    1431231c496e4bd8acc4055f3150a3f4:
      title: A Sādhana of Golden Mañjughoṣa
      parent: Sādhanas
    4cf7bd7a027e4044b74944523764745a:
      title: A Sādhana of Tārā Sarasvatī
      parent: Sādhanas
    ff8b78a16153446cafcaae446f098a64:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    25154ca2c2b549f78160ea6c0ab4f0f6:
      title: Daily Practice of Guru Rinpoche, Buddha of Medicine
      parent: Sādhanas
    5142238d0e924773b2544a7b54d50916:
      title: 'The Refined Essence of Compassion: A Daily Sādhana for the Natural Liberation
        of Suffering, the Secret Practice of the Great Compassionate One'
      parent: Sādhanas
    77d864b81f6f4f4a8479c18e3375e7a4:
      title: Lamenting Prayer to Jamyang Chökyi Lodrö
      parent: Swift Rebirth Prayers
    b8f4c596cac44d629dbe1ab425c1cc31:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Tsok Offering
created_at: '2022-02-28T22:53:20.383387'
last_modified_at: '2022-02-28T22:53:20.383389'
